use find_college_db;
DELETE  FROM MARKS;
ALTER TABLE MARKS AUTO_INCREMENT = 1;
INSERT INTO MARKS(ENGLISH,HINDI_KANNADA,MATHS,PHYSICS,CHEMISTRY,COMPUTER_BIOLOGY) VALUES(60,60,60,60,60,60);
SELECT * FROM MARKS;
